//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuLiLoan.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.LoanMoney = new HashSet<LoanMoney>();
        }
    
        public short Lid { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string IdCard { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public string IdImgPlus { get; set; }
        public string IdImgMinus { get; set; }
        public string IdImgHand { get; set; }
        public string ApplyTable { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanMoney> LoanMoney { get; set; }
    }
}
