//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuLiLoan.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLoanMoney
    {
        public string Name { get; set; }
        public string UserName { get; set; }
        public string IdCard { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public short Lid { get; set; }
        public double Money { get; set; }
        public System.DateTime Approvetime { get; set; }
        public System.DateTime LimitTime { get; set; }
        public double LoanTime { get; set; }
        public double Interest { get; set; }
        public string Status { get; set; }
    }
}
